name: Deploy Plugin to Multiple Sites
on:
  push:
    branches:
      - main  # Sadece main branch'e push yapıldığında çalışır

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Buraya güncellemek istediğiniz her sitenin IP/Host bilgisini ekleyin
        site: [algoritmagunlukleri.com] 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ matrix.site }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "."
          # WordPress plugin dizininizin tam yolunu yazın
          target: "/home/u260227757/domains/algoritmagunlukleri.com/public_html/wp-content/plugins/aimakale"
          strip_components: 0
